### ISSUE TITLE
Start committing to master branch directly

### ISSUE THREAD

**Issue by profnandaa** [uonbi/codejam#2]
Hey Denno, 
Start committing to this repo directly, other than sending pull requests. I guess you have read/write access to it.

Keep up the good job!

**Comment by janja-janja** [comment]
```
                                                                                                                                 Thanks Prof.                                                                                                                                                                                                                                          From: Anthony NandaaSent: Sunday, February 8, 2015 01:14To: uonbi/codejamReply To: uonbi/codejamCc: Denis KaranjaSubject: [codejam] Start committing to master branch directly (#2)Hey Denno, 
```

Start committing to this repo directly, other than sending pull requests. I guess you have read/write access to it.

Keep up the good job!

—Reply to this email directly or view it on GitHub.

**Comment by profnandaa** [comment]
Hope it's now okay, you just clone this repo.

**Comment by janja-janja** [comment]
Yeah it is now.                                                                                                                                                                                                                                                                                                                                                                               From: Anthony NandaaSent: Tuesday, February 10, 2015 23:55To: uonbi/codejamReply To: uonbi/codejamCc: Denis KaranjaSubject: Re: [codejam] Start committing to master branch directly (#2)Hope it's now okay, you just clone this repo.

—Reply to this email directly or view it on GitHub.
